### PR TITLE
Add test case and fix for escaped forward slashes.

### LINKED ISSUE #44: Unable to match escaped forward-slashes
I want to match between a set of multi-line C-style (`/*` `*/`) style comments which get displayed at the package level in the godoc tool. For example: [doc.go source](https://golang.org/src/encoding/gob/doc.go) -> [godoc preview](https://golang.org/pkg/encoding/gob/)

But I get an `unbalanced /` error when trying to escape values with the regexps: `/\/\*/` or `/\*\//`

I'd imagine this would also cause issues when attempting to match a file path, or URL.

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #44 

Let me know what you think!

### CODE REVIEW

File: embedmd/command.go [hunk 1]
```diff
@@ -68,20 +68,38 @@ func fields(s string) ([]string, error) {
...
 
 	for s = strings.TrimSpace(s); len(s) > 0; s = strings.TrimSpace(s) {
+		var sep int
 		if s[0] == '/' {
-			sep := strings.IndexByte(s[1:], '/')
+			sep = nextSlash(s, 1)
 			if sep < 0 {
 				return nil, errors.New("unbalanced /")
 			}
-			args, s = append(args, s[:sep+2]), s[sep+2:]
```
Comment (bbrks) [inline embedmd/command.go]: Explanation: We no longer have this special case if we pre-define the offset as 1 in the `nextSlash` call above so can move it outside of the if/else block.

File: embedmd/command.go [hunk 2]
```diff
@@ -68,20 +68,38 @@ func fields(s string) ([]string, error) {
...
+
+// nextSlash will find the index of the next unescaped slash in a string.
+func nextSlash(s string, offset int) int {
+	sep := strings.IndexByte(s[offset:], '/')
+	if sep < 0 {
+		return sep
+	}
+
+	// build up an offset for the original string.
+	sep += offset
```
Comment (bbrks) [inline embedmd/command.go]: Explanation: This is so that recursed calls will bubble up an offset against the original string, rather than for the subslice they actually get an index for.

File: embedmd/command.go [hunk 3]
```diff
@@ -68,20 +68,38 @@ func fields(s string) ([]string, error) {
...
+
+	// recurse if the slash we found is escaped.
+	if s[sep-1] == '\\' {
```
Comment (campoy) [inline embedmd/command.go]: this is probably not a good candidate for recursion, why not simply a for loop?

```go
func nextSlash(s string) int {
	for sep := 0; ; sep++ {
		i := strings.IndexByte(s[sep:], '/')
		if i < 0 {
			return -1
		}
		sep += i
		if sep == 0 || s[sep-1] != '\\' {
			return sep
		}
	}
}
```

**Comment by bbrks** [comment]
I signed it!
